export const MOCK_WALLET = {
  address: '0x7a3B...4f2E',
  usdcBalance: 42500.00,
  arcMindShares: 85230.45,
  maxWithdraw: 78100.00,
};

export const MOCK_VAULT = {
  totalAssets: 312750.00,
  localBalance: 31275.00,
  remoteCapital: 281475.00,
};

export const MOCK_AGENTS = [
  {
    chain: 'BASE',
    running: true,
    cycleCount: 847,
    currentCapital: 85000,
    positions: 3,
    safety: 0.93,
    confidence: 0.87,
    topYield: 6.5,
    optimalCapital: 95000,
    last7dYield: 5.8,
    accuracy: 0.84,
    strategy: [
      { protocol: 'Morpho V3', action: 'deposit' as const, amount_pct: 55, raw_yield: 6.8, post_deposit_yield: 5.9, reasoning: 'Vault #3 curated by Steakhouse' },
      { protocol: 'Aave V3', action: 'deposit' as const, amount_pct: 30, raw_yield: 4.2, post_deposit_yield: 4.0, reasoning: 'Deep liquidity, low risk' },
      { protocol: 'Compound V3', action: 'deposit' as const, amount_pct: 15, raw_yield: 3.8, post_deposit_yield: 3.7, reasoning: 'Safety buffer' },
    ],
    harvest: { pending_rewards_usd: 142, harvest_profitable: true, optimal_harvest_time: 'now' },
    curve: [
      { capital: 10000, blended_yield: 6.5 },
      { capital: 20000, blended_yield: 6.1 },
      { capital: 35000, blended_yield: 5.6 },
      { capital: 50000, blended_yield: 5.2 },
      { capital: 75000, blended_yield: 4.3 },
      { capital: 100000, blended_yield: 3.5 },
    ],
  },
  {
    chain: 'ARB',
    running: true,
    cycleCount: 831,
    currentCapital: 72000,
    positions: 2,
    safety: 0.91,
    confidence: 0.82,
    topYield: 5.6,
    optimalCapital: 80000,
    last7dYield: 5.1,
    accuracy: 0.79,
    strategy: [
      { protocol: 'Aave V3', action: 'deposit' as const, amount_pct: 60, raw_yield: 5.1, post_deposit_yield: 4.8, reasoning: 'High utilization' },
      { protocol: 'Morpho Blue', action: 'deposit' as const, amount_pct: 40, raw_yield: 5.6, post_deposit_yield: 5.1, reasoning: 'New vault, good curator' },
    ],
    harvest: { pending_rewards_usd: 89, harvest_profitable: true, optimal_harvest_time: '2h' },
    curve: [
      { capital: 10000, blended_yield: 5.6 },
      { capital: 20000, blended_yield: 5.3 },
      { capital: 35000, blended_yield: 4.9 },
      { capital: 50000, blended_yield: 4.4 },
      { capital: 75000, blended_yield: 3.8 },
      { capital: 100000, blended_yield: 3.1 },
    ],
  },
  {
    chain: 'ETH',
    running: true,
    cycleCount: 812,
    currentCapital: 55000,
    positions: 3,
    safety: 0.95,
    confidence: 0.85,
    topYield: 3.8,
    optimalCapital: 50000,
    last7dYield: 3.4,
    accuracy: 0.88,
    strategy: [
      { protocol: 'Aave V3', action: 'deposit' as const, amount_pct: 45, raw_yield: 3.2, post_deposit_yield: 3.0, reasoning: 'Deepest liquidity in DeFi' },
      { protocol: 'Compound V3', action: 'deposit' as const, amount_pct: 30, raw_yield: 2.8, post_deposit_yield: 2.7, reasoning: 'Battle-tested' },
      { protocol: 'Morpho Blue', action: 'deposit' as const, amount_pct: 25, raw_yield: 4.5, post_deposit_yield: 4.1, reasoning: 'Higher yield curated vault' },
    ],
    harvest: { pending_rewards_usd: 215, harvest_profitable: true, optimal_harvest_time: 'now' },
    curve: [
      { capital: 10000, blended_yield: 3.8 },
      { capital: 20000, blended_yield: 3.5 },
      { capital: 35000, blended_yield: 3.2 },
      { capital: 50000, blended_yield: 2.9 },
      { capital: 75000, blended_yield: 2.4 },
      { capital: 100000, blended_yield: 1.9 },
    ],
  },
  {
    chain: 'AVAX',
    running: true,
    cycleCount: 798,
    currentCapital: 42000,
    positions: 2,
    safety: 0.89,
    confidence: 0.78,
    topYield: 4.2,
    optimalCapital: 45000,
    last7dYield: 3.9,
    accuracy: 0.76,
    strategy: [
      { protocol: 'Aave V3', action: 'deposit' as const, amount_pct: 70, raw_yield: 4.2, post_deposit_yield: 3.9, reasoning: 'Main lending on Avalanche' },
      { protocol: 'Benqi', action: 'deposit' as const, amount_pct: 30, raw_yield: 3.5, post_deposit_yield: 3.3, reasoning: 'Native AVAX lending' },
    ],
    harvest: { pending_rewards_usd: 67, harvest_profitable: true, optimal_harvest_time: '4h' },
    curve: [
      { capital: 10000, blended_yield: 4.2 },
      { capital: 20000, blended_yield: 3.9 },
      { capital: 35000, blended_yield: 3.5 },
      { capital: 50000, blended_yield: 3.1 },
      { capital: 75000, blended_yield: 2.5 },
      { capital: 100000, blended_yield: 2.0 },
    ],
  },
  {
    chain: 'OP',
    running: true,
    cycleCount: 785,
    currentCapital: 27475,
    positions: 2,
    safety: 0.87,
    confidence: 0.75,
    topYield: 3.9,
    optimalCapital: 30000,
    last7dYield: 3.5,
    accuracy: 0.73,
    strategy: [
      { protocol: 'Aave V3', action: 'deposit' as const, amount_pct: 65, raw_yield: 3.9, post_deposit_yield: 3.6, reasoning: 'Primary OP lending' },
      { protocol: 'Sonne Finance', action: 'deposit' as const, amount_pct: 35, raw_yield: 4.1, post_deposit_yield: 3.8, reasoning: 'OP incentives' },
    ],
    harvest: { pending_rewards_usd: 38, harvest_profitable: false, optimal_harvest_time: '12h' },
    curve: [
      { capital: 10000, blended_yield: 3.9 },
      { capital: 20000, blended_yield: 3.6 },
      { capital: 35000, blended_yield: 3.2 },
      { capital: 50000, blended_yield: 2.8 },
      { capital: 75000, blended_yield: 2.2 },
      { capital: 100000, blended_yield: 1.7 },
    ],
  },
];
